# Site settings
title: "Drew Levitt"
description: "Personal Website"
baseurl: ""
url: "https://Drelev.github.io"

# Theme settings
theme: jekyll-theme-minimal

# Optional settings
author: Drew Levitt
social_links:
  - https://github.com/yourusername
  - https://linkedin.com/in/yourprofile
  - https://twitter.com/yourhandle
